import { Candidate, MinistryType, CabinetState } from '@/types/cabinet';

/**
 * All 8 Union Ministries
 */
export const MINISTRIES: MinistryType[] = [
  'Finance',
  'Home Affairs',
  'Defence',
  'Education',
  'Health',
  'Agriculture',
  'Infrastructure',
  'External Affairs',
];

/**
 * Centralized Prototype Candidates Catalog (3 per ministry)
 */
export const CANDIDATES_CATALOG: Candidate[] = [
  // Finance
  {
    id: 'fin_cand_1',
    name: 'Aarav Sharma',
    age: 54,
    ministry: 'Finance',
    experience: 85,
    integrity: 95,
    popularity: 60,
    loyalty: 80,
    relationship: 82,
    shortDescription: 'Veteran economist focused on fiscal discipline and tax reforms.',
    status: 'Candidate',
  },
  {
    id: 'fin_cand_2',
    name: 'Vikramaditya Roy',
    age: 61,
    ministry: 'Finance',
    experience: 90,
    integrity: 65,
    popularity: 85,
    loyalty: 45,
    relationship: 60,
    shortDescription: 'High-profile industrial leader with strong market popularity.',
    status: 'Candidate',
  },
  {
    id: 'fin_cand_3',
    name: 'Priya Venkatesh',
    age: 48,
    ministry: 'Finance',
    experience: 65,
    integrity: 75,
    popularity: 90,
    loyalty: 88,
    relationship: 75,
    shortDescription: 'Charismatic financial reformer advocating welfare banking.',
    status: 'Candidate',
  },

  // Home Affairs
  {
    id: 'home_cand_1',
    name: 'Rajeshwar Singh',
    age: 58,
    ministry: 'Home Affairs',
    experience: 80,
    integrity: 70,
    popularity: 75,
    loyalty: 85,
    relationship: 78,
    shortDescription: 'Staunch administrator with firm national security credentials.',
    status: 'Candidate',
  },
  {
    id: 'home_cand_2',
    name: 'Amitabha Sen',
    age: 52,
    ministry: 'Home Affairs',
    experience: 92,
    integrity: 85,
    popularity: 55,
    loyalty: 60,
    relationship: 65,
    shortDescription: 'Former civil servant specializing in police reforms and internal security.',
    status: 'Candidate',
  },
  {
    id: 'home_cand_3',
    name: 'Sunita Deshmukh',
    age: 50,
    ministry: 'Home Affairs',
    experience: 70,
    integrity: 90,
    popularity: 88,
    loyalty: 92,
    relationship: 85,
    shortDescription: 'Grassroots leader known for high integrity and public trust.',
    status: 'Candidate',
  },

  // Defence
  {
    id: 'def_cand_1',
    name: 'Gen. (Retd.) K.S. Rathore',
    age: 64,
    ministry: 'Defence',
    experience: 95,
    integrity: 90,
    popularity: 70,
    loyalty: 75,
    relationship: 80,
    shortDescription: 'Decorated commander focused on military modernization.',
    status: 'Candidate',
  },
  {
    id: 'def_cand_2',
    name: 'Devendra Varma',
    age: 56,
    ministry: 'Defence',
    experience: 75,
    integrity: 60,
    popularity: 80,
    loyalty: 85,
    relationship: 72,
    shortDescription: 'Defense analyst with strong parliamentary backing.',
    status: 'Candidate',
  },
  {
    id: 'def_cand_3',
    name: 'Meera Chawla',
    age: 49,
    ministry: 'Defence',
    experience: 60,
    integrity: 95,
    popularity: 75,
    loyalty: 90,
    relationship: 88,
    shortDescription: 'Diplomatic defense specialist emphasizing border infrastructure.',
    status: 'Candidate',
  },

  // Education
  {
    id: 'edu_cand_1',
    name: 'Prof. Hitesh Bannerjee',
    age: 57,
    ministry: 'Education',
    experience: 85,
    integrity: 90,
    popularity: 65,
    loyalty: 82,
    relationship: 79,
    shortDescription: 'Renowned academician promoting STEM & digital learning networks.',
    status: 'Candidate',
  },
  {
    id: 'edu_cand_2',
    name: 'Shalini Mukherji',
    age: 46,
    ministry: 'Education',
    experience: 60,
    integrity: 80,
    popularity: 92,
    loyalty: 70,
    relationship: 70,
    shortDescription: 'Dynamic youth leader focused on vocational skill universities.',
    status: 'Candidate',
  },
  {
    id: 'edu_cand_3',
    name: 'Anand Kumar',
    age: 51,
    ministry: 'Education',
    experience: 75,
    integrity: 95,
    popularity: 85,
    loyalty: 95,
    relationship: 90,
    shortDescription: 'Passionate educator advocating equitable rural education access.',
    status: 'Candidate',
  },

  // Health
  {
    id: 'hlt_cand_1',
    name: 'Dr. Arishta Kulkarni',
    age: 53,
    ministry: 'Health',
    experience: 88,
    integrity: 92,
    popularity: 78,
    loyalty: 80,
    relationship: 81,
    shortDescription: 'Public health expert who spearheaded national medical reforms.',
    status: 'Candidate',
  },
  {
    id: 'hlt_cand_2',
    name: 'Dr. Someshwar Rao',
    age: 59,
    ministry: 'Health',
    experience: 94,
    integrity: 70,
    popularity: 60,
    loyalty: 75,
    relationship: 68,
    shortDescription: 'Senior surgeon and veteran hospital administrator.',
    status: 'Candidate',
  },
  {
    id: 'hlt_cand_3',
    name: 'Ananya Sen',
    age: 44,
    ministry: 'Health',
    experience: 55,
    integrity: 85,
    popularity: 90,
    loyalty: 88,
    relationship: 85,
    shortDescription: 'Community healthcare champion advocating generic medicine access.',
    status: 'Candidate',
  },

  // Agriculture
  {
    id: 'agr_cand_1',
    name: 'Balwinder Singh Dhillon',
    age: 60,
    ministry: 'Agriculture',
    experience: 85,
    integrity: 75,
    popularity: 88,
    loyalty: 80,
    relationship: 76,
    shortDescription: 'Prominent agrarian leader advocating MSP protection and crop safety.',
    status: 'Candidate',
  },
  {
    id: 'agr_cand_2',
    name: 'Raghunath Patil',
    age: 55,
    ministry: 'Agriculture',
    experience: 70,
    integrity: 90,
    popularity: 70,
    loyalty: 92,
    relationship: 84,
    shortDescription: 'Progressive farmer pioneer emphasizing micro-irrigation.',
    status: 'Candidate',
  },
  {
    id: 'agr_cand_3',
    name: 'Savitri Devi',
    age: 52,
    ministry: 'Agriculture',
    experience: 65,
    integrity: 95,
    popularity: 82,
    loyalty: 85,
    relationship: 80,
    shortDescription: 'Rural cooperative leader empowering women farmers.',
    status: 'Candidate',
  },

  // Infrastructure
  {
    id: 'inf_cand_1',
    name: 'N.K. Srinivas',
    age: 56,
    ministry: 'Infrastructure',
    experience: 90,
    integrity: 80,
    popularity: 75,
    loyalty: 85,
    relationship: 83,
    shortDescription: 'Infrastructure wizard known for rapid expressway construction.',
    status: 'Candidate',
  },
  {
    id: 'inf_cand_2',
    name: 'Harshwardhan Joshi',
    age: 50,
    ministry: 'Infrastructure',
    experience: 75,
    integrity: 65,
    popularity: 88,
    loyalty: 60,
    relationship: 65,
    shortDescription: 'High-energy urban transit innovator.',
    status: 'Candidate',
  },
  {
    id: 'inf_cand_3',
    name: 'Tarun Kapoor',
    age: 58,
    ministry: 'Infrastructure',
    experience: 82,
    integrity: 92,
    popularity: 60,
    loyalty: 90,
    relationship: 88,
    shortDescription: 'Disciplined administrator delivering freight corridor projects.',
    status: 'Candidate',
  },

  // External Affairs
  {
    id: 'ext_cand_1',
    name: 'Amb. S.K. Jaideep',
    age: 62,
    ministry: 'External Affairs',
    experience: 96,
    integrity: 90,
    popularity: 82,
    loyalty: 85,
    relationship: 86,
    shortDescription: 'Veteran diplomat renowned for strategic autonomy and global negotiations.',
    status: 'Candidate',
  },
  {
    id: 'ext_cand_2',
    name: 'Natwar Varma',
    age: 57,
    ministry: 'External Affairs',
    experience: 80,
    integrity: 75,
    popularity: 70,
    loyalty: 90,
    relationship: 78,
    shortDescription: 'Foreign policy analyst specializing in multilateral trade treaties.',
    status: 'Candidate',
  },
  {
    id: 'ext_cand_3',
    name: 'Radhika Iyer',
    age: 48,
    ministry: 'External Affairs',
    experience: 65,
    integrity: 95,
    popularity: 85,
    loyalty: 92,
    relationship: 90,
    shortDescription: 'Dynamic international relations strategist promoting diaspora engagement.',
    status: 'Candidate',
  },
];

/**
 * Initial Cabinet State (7 filled, 1 vacant for immediate playable test)
 */
export const INITIAL_CABINET_STATE: CabinetState = {
  ministers: {
    Finance: { ...CANDIDATES_CATALOG[0], status: 'Active' }, // Aarav Sharma
    'Home Affairs': { ...CANDIDATES_CATALOG[3], status: 'Active' }, // Rajeshwar Singh
    Defence: { ...CANDIDATES_CATALOG[6], status: 'Active' }, // Gen. K.S. Rathore
    Education: { ...CANDIDATES_CATALOG[9], status: 'Active' }, // Prof. Hitesh Bannerjee
    Health: { ...CANDIDATES_CATALOG[12], status: 'Active' }, // Dr. Arishta Kulkarni
    Agriculture: { ...CANDIDATES_CATALOG[15], status: 'Active' }, // Balwinder Singh Dhillon
    Infrastructure: { ...CANDIDATES_CATALOG[18], status: 'Active' }, // N.K. Srinivas
    'External Affairs': null, // Vacant initially!
  },
};
