import { GameEvent } from '@/types/event';

/**
 * 10 Handcrafted Random Events Catalog
 */
export const HANDCRAFTED_EVENTS_CATALOG: GameEvent[] = [
  {
    id: 'assam_floods_event',
    title: 'Assam Floods Crisis',
    category: 'Natural Disaster',
    severity: 'High',
    description: 'Torrential monsoon rains have inundated over 20 districts in Assam, stranding hundreds of thousands of citizens.',
    options: [
      {
        id: 'opt_assam_relief',
        title: 'Emergency Relief & NDRF Package',
        description: 'Deploy NDRF battalions and release emergency relief funds for food, medicine, and temporary shelters.',
        pros: 'Immediate humanitarian relief & surge in public approval.',
        cons: 'High treasury expenditure & minor inflation.',
        effects: { treasury: -500, popularity: 4, gdp: -0.1, inflation: 0.1, unemployment: 0 },
      },
      {
        id: 'opt_assam_coord',
        title: 'State-Central Joint Coordination',
        description: 'Establish a joint relief taskforce with state authorities with equal cost sharing.',
        pros: 'Shared financial burden & cooperative federalism.',
        cons: 'Slower deployment speed.',
        effects: { treasury: -200, popularity: 2, gdp: 0, inflation: 0, unemployment: 0 },
      },
      {
        id: 'opt_assam_survey',
        title: 'Dispatch Parliamentary Study Committee',
        description: 'Send an assessment team before committing major central funds.',
        pros: 'Minimal upfront budget impact.',
        cons: 'Public outcry over delayed emergency response.',
        effects: { treasury: -50, popularity: -5, gdp: -0.2, inflation: 0, unemployment: 0 },
      },
    ],
  },
  {
    id: 'severe_heatwave_event',
    title: 'Severe Heatwave Alert',
    category: 'Natural Disaster',
    severity: 'Medium',
    description: 'Unprecedented summer temperatures across Central & Northern India threaten crop yields and public health.',
    options: [
      {
        id: 'opt_heat_emergency',
        title: 'Emergency Water & Cooling Package',
        description: 'Dispatch mobile water tankers, set up cooling centers, and subsidize power for irrigation.',
        pros: 'Prevents health casualties & protects agricultural yields.',
        cons: 'Moderate treasury expenditure.',
        effects: { treasury: -300, popularity: 3, gdp: 0, inflation: 0.1, unemployment: 0 },
      },
      {
        id: 'opt_heat_crop_support',
        title: 'Targeted Crop Protection Grant',
        description: 'Provide direct financial grants to small farmers for drought-resistant inputs.',
        pros: 'Sustains rural farm confidence.',
        cons: 'Requires administrative distribution time.',
        effects: { treasury: -150, popularity: 2, gdp: 0.1, inflation: 0, unemployment: 0 },
      },
      {
        id: 'opt_heat_advisory',
        title: 'Issue National Public Advisory',
        description: 'Advise state governments and citizens to adjust work hours without extra federal funding.',
        pros: 'Zero direct treasury drain.',
        cons: 'Public dissatisfaction over lack of direct assistance.',
        effects: { treasury: 0, popularity: -2, gdp: -0.1, inflation: 0, unemployment: 0 },
      },
    ],
  },
  {
    id: 'oil_price_shock_event',
    title: 'Global Oil Price Shock',
    category: 'Economy',
    severity: 'Critical',
    description: 'International crude oil prices have surged suddenly due to geopolitical tensions, threatening national import bills.',
    options: [
      {
        id: 'opt_oil_subsidy',
        title: 'Increase Fuel Subsidies',
        description: 'Absorb price shocks at state oil companies to keep retail petrol and diesel prices stable.',
        pros: 'Protects consumer purchasing power and controls inflation.',
        cons: 'Heavy drain on national treasury.',
        effects: { treasury: -700, popularity: 3, gdp: 0, inflation: -0.1, unemployment: 0 },
      },
      {
        id: 'opt_oil_market_pass',
        title: 'Allow Fuel Prices to Rise',
        description: 'Pass global price increases directly to consumers without central intervention.',
        pros: 'Preserves treasury reserves.',
        cons: 'Sharp inflation spike & public discontent.',
        effects: { treasury: 0, popularity: -4, gdp: -0.2, inflation: 0.5, unemployment: 0.1 },
      },
      {
        id: 'opt_oil_tax_cut',
        title: 'Temporary Fuel Excise Cut',
        description: 'Reduce central excise duties on petrol and diesel to cushion retail prices.',
        pros: 'Balanced protection for consumers and transportation sector.',
        cons: 'Moderate loss of government tax revenue.',
        effects: { treasury: -350, popularity: 2, gdp: 0.1, inflation: 0.1, unemployment: 0 },
      },
    ],
  },
  {
    id: 'stock_market_crash_event',
    title: 'Stock Market Volatility Crash',
    category: 'Economy',
    severity: 'High',
    description: 'Global equity sell-offs have triggered a 7% single-day drop in domestic stock indices, panicking retail investors.',
    options: [
      {
        id: 'opt_market_bank_liquidity',
        title: 'Inject Banking System Liquidity',
        description: 'Authorize RBI and public sector banks to support institutional market liquidity.',
        pros: 'Restores investor confidence & stabilizes financial markets.',
        cons: 'Substantial central liquidity commitment.',
        effects: { treasury: -600, popularity: 2, gdp: 0.2, inflation: 0.2, unemployment: -0.1 },
      },
      {
        id: 'opt_market_stabilization',
        title: 'Create Market Stabilization Fund',
        description: 'Establish a sovereign buffer fund to purchase blue-chip equity assets.',
        pros: 'Demonstrates strong state backing for capital markets.',
        cons: 'Exposes state funds to market risk.',
        effects: { treasury: -300, popularity: 1, gdp: 0.1, inflation: 0.1, unemployment: 0 },
      },
      {
        id: 'opt_market_statement',
        title: 'Issue Economic Confidence Statement',
        description: 'Reassure markets that macroeconomic fundamentals remain solid without intervention.',
        pros: 'Zero cost to government treasury.',
        cons: 'Short-term volatility continues.',
        effects: { treasury: 0, popularity: -1, gdp: -0.1, inflation: 0, unemployment: 0 },
      },
    ],
  },
  {
    id: 'farmers_protest_event',
    title: 'Farmers Agitation & Highway Blockade',
    category: 'Agriculture',
    severity: 'High',
    description: 'Agricultural unions have organized mass demonstrations demanding higher Minimum Support Prices (MSP).',
    options: [
      {
        id: 'opt_protest_msp_increase',
        title: 'Increase Guaranteed MSP Rates',
        description: 'Announce a major hike in minimum support prices for major kharif and rabi crops.',
        pros: 'Ends protests immediately & boosts rural popularity.',
        cons: 'Increases food subsidy budget & mild food inflation.',
        effects: { treasury: -500, popularity: 5, gdp: 0.1, inflation: 0.2, unemployment: 0 },
      },
      {
        id: 'opt_protest_panel',
        title: 'Form Ministerial Negotiation Panel',
        description: 'Invite protest leaders to PMO talks while setting up a statutory review committee.',
        pros: 'Peaceful dialogue without immediate fiscal commitment.',
        cons: 'Protests continue in the short term.',
        effects: { treasury: -100, popularity: 1, gdp: 0, inflation: 0, unemployment: 0 },
      },
      {
        id: 'opt_protest_enforce_law',
        title: 'Enforce Public Order & Traffic Clearance',
        description: 'Instruct state police to clear highway blockades to ensure free commercial movement.',
        pros: 'Restores national logistics & trade movement.',
        cons: 'Heavy backlash from rural farming communities.',
        effects: { treasury: 0, popularity: -4, gdp: 0.1, inflation: 0, unemployment: 0 },
      },
    ],
  },
  {
    id: 'disease_outbreak_event',
    title: 'Regional Viral Outbreak Alert',
    category: 'Healthcare',
    severity: 'Critical',
    description: 'Health authorities report a cluster of severe viral infection cases across southern coastal districts.',
    options: [
      {
        id: 'opt_outbreak_vaccine_campaign',
        title: 'Mass Emergency Vaccination & ICU Campaign',
        description: 'Deploy national medical reserves, construct emergency isolation wards, and distribute free antivirals.',
        pros: 'Rapid epidemic containment & high public trust in government.',
        cons: 'Significant emergency health budget drain.',
        effects: { treasury: -550, popularity: 5, gdp: 0.1, inflation: 0, unemployment: -0.1 },
      },
      {
        id: 'opt_outbreak_quarantine',
        title: 'Targeted District Quarantines & Testing',
        description: 'Enforce localized containment zones and expand door-to-door diagnostic testing.',
        pros: 'Balanced healthcare expenditure.',
        cons: 'Temporary disruption to local economic activity.',
        effects: { treasury: -250, popularity: 2, gdp: -0.1, inflation: 0, unemployment: 0 },
      },
      {
        id: 'opt_outbreak_alert',
        title: 'Issue Standard Health Department Alert',
        description: 'Delegate containment operations entirely to state health departments.',
        pros: 'Minimal central treasury impact.',
        cons: 'Risk of wider outbreak and severe public criticism.',
        effects: { treasury: -50, popularity: -4, gdp: -0.2, inflation: 0, unemployment: 0 },
      },
    ],
  },
  {
    id: 'infrastructure_failure_event',
    title: 'Major Highway Bridge Failure',
    category: 'Infrastructure',
    severity: 'Medium',
    description: 'A key structural bridge on a major national freight corridor has collapsed due to flood damage, paralyzing regional freight.',
    options: [
      {
        id: 'opt_infra_fasttrack_rebuild',
        title: 'Fast-Track Army Engineer Reconstruction',
        description: 'Deploy Military Engineering Services to build a temporary pontoon bridge and rebuild permanently.',
        pros: 'Restores freight trade within days & demonstrates administrative speed.',
        cons: 'Substantial emergency reconstruction expenditure.',
        effects: { treasury: -400, popularity: 3, gdp: 0.2, inflation: 0.1, unemployment: -0.1 },
      },
      {
        id: 'opt_infra_reroute',
        title: 'Regional Traffic Rerouting Plan',
        description: 'Divert heavy freight through state highways while tendering normal repairs.',
        pros: 'Lower immediate government cost.',
        cons: 'Increases logistics delay and transport costs.',
        effects: { treasury: -150, popularity: 1, gdp: 0, inflation: 0.1, unemployment: 0 },
      },
      {
        id: 'opt_infra_enquiry',
        title: 'Order Departmental Safety Inquiry',
        description: 'Commission a safety audit before approving reconstruction funds.',
        pros: 'Zero immediate emergency spending.',
        cons: 'Prolonged trade bottleneck and public anger.',
        effects: { treasury: -30, popularity: -3, gdp: -0.1, inflation: 0, unemployment: 0 },
      },
    ],
  },
  {
    id: 'isro_mission_success_event',
    title: 'ISRO Space Mission Triumph',
    category: 'Science',
    severity: 'Low',
    description: 'ISRO has successfully placed a next-generation lunar exploration satellite into orbit, placing India among elite space nations.',
    options: [
      {
        id: 'opt_isro_expand_budget',
        title: 'Expand Space & Deep-Tech R&D Budget',
        description: 'Announce additional funding for human spaceflight and indigenous satellite tech.',
        pros: 'Surge in national pride & long-term technological advancement.',
        cons: 'Moderate investment from national treasury.',
        effects: { treasury: -300, popularity: 5, gdp: 0.2, inflation: 0, unemployment: -0.1 },
      },
      {
        id: 'opt_isro_space_day',
        title: 'Declare National Space Tech Day',
        description: 'Institute student scholarships and national science awards.',
        pros: 'Inspires youth while maintaining budget discipline.',
        cons: 'Modest economic impact.',
        effects: { treasury: -50, popularity: 3, gdp: 0.1, inflation: 0, unemployment: 0 },
      },
      {
        id: 'opt_isro_commendation',
        title: 'Issue Official PM Commendation Message',
        description: 'Congratulate ISRO scientists publicly without budget expansion.',
        pros: 'Zero treasury cost.',
        cons: 'Missed opportunity for space industry expansion.',
        effects: { treasury: 0, popularity: 2, gdp: 0, inflation: 0, unemployment: 0 },
      },
    ],
  },
  {
    id: 'foreign_investment_event',
    title: 'Major Foreign Tech Investment Proposal',
    category: 'Economy',
    severity: 'Medium',
    description: 'A global semiconductor conglomerate proposes establishing a $10 Billion manufacturing mega-fab in India.',
    options: [
      {
        id: 'opt_fdi_fasttrack_subsidy',
        title: 'Provide Production Linked Incentive (PLI)',
        description: 'Offer capital subsidies and dedicated land & power infrastructure.',
        pros: 'Massive long-term GDP growth & thousands of high-tech jobs.',
        cons: 'Requires upfront state infrastructure subsidy.',
        effects: { treasury: -200, popularity: 4, gdp: 0.5, inflation: 0.1, unemployment: -0.3 },
      },
      {
        id: 'opt_fdi_standard_zone',
        title: 'Allocate Industrial Park Land',
        description: 'Offer standard industrial park plot with single-window clearances.',
        pros: 'Balanced fiscal incentive with strong job creation.',
        cons: 'Slightly slower construction timeline.',
        effects: { treasury: -100, popularity: 2, gdp: 0.3, inflation: 0, unemployment: -0.2 },
      },
      {
        id: 'opt_fdi_tax_rebate',
        title: 'Offer Future Tax Rebates Only',
        description: 'Provide long-term corporate tax concessions without direct capital subsidies.',
        pros: 'Zero immediate cash outlay from treasury.',
        cons: 'Slight risk of investor choosing competing nations.',
        effects: { treasury: 0, popularity: 1, gdp: 0.2, inflation: 0, unemployment: -0.1 },
      },
    ],
  },
  {
    id: 'cricket_victory_event',
    title: 'India Wins World Cricket Tournament',
    category: 'Sports',
    severity: 'Low',
    description: 'The Indian national cricket team has won the International Cricket Championship in a dramatic final match.',
    options: [
      {
        id: 'opt_cricket_cash_award',
        title: 'Declare National Celebration & Youth Sports Fund',
        description: 'Announce cash honors for players and establish 100 sports academies nationwide.',
        pros: 'Enormous wave of national euphoria & public popularity.',
        cons: 'Minor treasury expenditure.',
        effects: { treasury: -100, popularity: 4, gdp: 0, inflation: 0, unemployment: 0 },
      },
      {
        id: 'opt_cricket_academies',
        title: 'Build Regional Multi-Sports Complexes',
        description: 'Channel momentum into building grassroots facilities for athletics, hockey, and cricket.',
        pros: 'Long-term sports infrastructure development.',
        cons: 'Higher initial construction outlay.',
        effects: { treasury: -250, popularity: 3, gdp: 0.1, inflation: 0, unemployment: -0.1 },
      },
      {
        id: 'opt_cricket_pmo_reception',
        title: 'Host PMO Honors Reception',
        description: 'Felicitate the winning team at the Prime Minister\'s residence.',
        pros: 'High media coverage at minimal cost.',
        cons: 'No new sports infrastructure created.',
        effects: { treasury: 0, popularity: 2, gdp: 0, inflation: 0, unemployment: 0 },
      },
    ],
  },
];
