import { Decision } from '@/types/decision';

/**
 * Centralized Policies & Decisions Catalog
 */

export const POLICIES_CATALOG: Decision[] = [
  {
    id: 'economic_stimulus',
    title: 'Economic Stimulus',
    category: 'Economy',
    description: 'A proposal to increase public spending to stimulate economic growth.',
    situation: 'Industrial output and consumer spending require public stimulus to accelerate GDP growth and job creation.',
    urgency: 'High',
    estimatedCost: '₹ 800 Cr',
    status: 'Available',
    options: [
      {
        id: 'opt_large_stimulus',
        title: 'Large Stimulus Package',
        description: 'Inject massive capital into key manufacturing sectors and infrastructure projects.',
        pros: 'Significant GDP expansion & rapid job creation.',
        cons: 'Heavy treasury drain & higher inflationary pressure.',
        effects: {
          treasury: -800,
          gdp: 0.4,
          popularity: 3,
          inflation: 0.3,
          unemployment: -0.3,
        },
      },
      {
        id: 'opt_mod_stimulus',
        title: 'Moderate Targeted Stimulus',
        description: 'Provide credit guarantees and targeted tax rebates for small and medium enterprises.',
        pros: 'Balanced fiscal expenditure with steady growth.',
        cons: 'Moderate immediate popularity increase.',
        effects: {
          treasury: -400,
          gdp: 0.2,
          popularity: 1,
          inflation: 0.1,
          unemployment: -0.1,
        },
      },
      {
        id: 'opt_no_stimulus',
        title: 'No Stimulus (Fiscal Discipline)',
        description: 'Maintain existing budget limits and rely on private market adjustments.',
        pros: 'Zero treasury drain & complete inflation control.',
        cons: 'Slight economic contraction & public discontent.',
        effects: {
          treasury: 0,
          gdp: -0.1,
          popularity: -2,
          inflation: 0,
          unemployment: 0.2,
        },
      },
    ],
  },
  {
    id: 'national_education_reform',
    title: 'National Education Reform',
    category: 'Education',
    description: 'A nationwide initiative to improve school infrastructure and learning outcomes.',
    situation: 'Outdated learning materials and infrastructure gaps hinder student development across public schools.',
    urgency: 'Medium',
    estimatedCost: '₹ 500 Cr',
    status: 'Available',
    options: [
      {
        id: 'opt_digital_education',
        title: 'Comprehensive Digital Upgrade',
        description: 'Equip public schools with digital labs, high-speed internet, and smart learning tools.',
        pros: 'High long-term human capital & strong public approval.',
        cons: 'Higher initial implementation cost.',
        effects: {
          treasury: -500,
          gdp: 0.3,
          popularity: 4,
          inflation: 0,
          unemployment: -0.1,
        },
      },
      {
        id: 'opt_targeted_education',
        title: 'Targeted School Modernization',
        description: 'Upgrade essential sanitation, textbooks, and teacher training in underdeveloped districts.',
        pros: 'Cost-effective with immediate baseline improvement.',
        cons: 'Limited national publicity impact.',
        effects: {
          treasury: -250,
          gdp: 0.1,
          popularity: 2,
          inflation: 0,
          unemployment: 0,
        },
      },
    ],
  },
  {
    id: 'healthcare_expansion',
    title: 'Healthcare Expansion',
    category: 'Healthcare',
    description: 'Increase public healthcare funding and expand access to hospitals.',
    situation: 'Rural districts require modern diagnostic equipment, emergency care units, and affordable healthcare.',
    urgency: 'High',
    estimatedCost: '₹ 600 Cr',
    status: 'Available',
    options: [
      {
        id: 'opt_universal_hospitals',
        title: 'Universal Hospital Network',
        description: 'Build regional multi-specialty hospitals and offer universal emergency health coverage.',
        pros: 'Major surge in public trust & nationwide healthcare access.',
        cons: 'Substantial upfront treasury commitment.',
        effects: {
          treasury: -600,
          gdp: 0.2,
          popularity: 5,
          inflation: 0.1,
          unemployment: -0.2,
        },
      },
      {
        id: 'opt_district_clinics',
        title: 'District Wellness Clinics',
        description: 'Establish primary care clinics across all sub-districts with essential diagnostic tools.',
        pros: 'Moderate cost with rapid rollout across rural areas.',
        cons: 'Slower impact on specialized medical care.',
        effects: {
          treasury: -300,
          gdp: 0.1,
          popularity: 3,
          inflation: 0,
          unemployment: -0.1,
        },
      },
    ],
  },
  {
    id: 'agricultural_support_package',
    title: 'Agricultural Support Package',
    category: 'Agriculture',
    description: 'Provide additional financial support to farmers during difficult conditions.',
    situation: 'Fluctuating crop yields and high fertilizer costs threaten rural financial stability.',
    urgency: 'High',
    estimatedCost: '₹ 400 Cr',
    status: 'Available',
    options: [
      {
        id: 'opt_direct_farm_aid',
        title: 'Direct Financial Assistance',
        description: 'Issue direct crop insurance subsidies and direct cash transfers to small farmers.',
        pros: 'Immediate relief to rural families & strong political support.',
        cons: 'Does not build permanent agricultural infrastructure.',
        effects: {
          treasury: -400,
          gdp: 0.1,
          popularity: 4,
          inflation: 0,
          unemployment: 0,
        },
      },
      {
        id: 'opt_irrigation_infrastructure',
        title: 'Subsidized Irrigation Systems',
        description: 'Subsidize micro-irrigation systems, drip farming kits, and solar water pumps.',
        pros: 'Long-term agricultural productivity & water conservation.',
        cons: 'Takes time for full economic returns.',
        effects: {
          treasury: -200,
          gdp: 0.2,
          popularity: 2,
          inflation: 0,
          unemployment: -0.1,
        },
      },
    ],
  },
  {
    id: 'national_infrastructure_push',
    title: 'National Infrastructure Push',
    category: 'Infrastructure',
    description: 'Accelerate investment in roads, railways and public infrastructure.',
    situation: 'Transport congestion and high freight costs hinder domestic manufacturing and trade.',
    urgency: 'High',
    estimatedCost: '₹ 900 Cr',
    status: 'Available',
    options: [
      {
        id: 'opt_expressway_freight',
        title: 'Expressways & Freight Corridors',
        description: 'Construct dedicated industrial freight corridors and high-speed multi-lane expressways.',
        pros: 'Massive long-term GDP boost & employment generation.',
        cons: 'Largest treasury expenditure with temporary inflation rise.',
        effects: {
          treasury: -900,
          gdp: 0.6,
          popularity: 3,
          inflation: 0.2,
          unemployment: -0.4,
        },
      },
      {
        id: 'opt_regional_connectivity',
        title: 'Regional Connectivity Upgrade',
        description: 'Modernize Tier-2 city railway stations and widen state highway networks.',
        pros: 'Balanced capital outlay with broad regional benefits.',
        cons: 'Less transformative than mega industrial corridors.',
        effects: {
          treasury: -450,
          gdp: 0.3,
          popularity: 2,
          inflation: 0.1,
          unemployment: -0.2,
        },
      },
    ],
  },
  {
    id: 'assam_flood_crisis',
    title: 'Flood in Assam',
    category: 'National',
    description: 'Heavy rainfall has caused severe flooding in Assam.',
    situation: 'Lives and infrastructure are at risk. People are expecting an immediate response.',
    urgency: 'High',
    estimatedCost: '₹ 500 Cr',
    status: 'Available',
    options: [
      {
        id: 'opt_a',
        title: 'Emergency Relief Package',
        description: 'Deploy NDRF forces immediately, distribute free rations, and release direct financial aid to flood victims.',
        pros: 'Immediate crisis response & significant boost to government popularity.',
        cons: 'Highest treasury drain & minor inflationary effect.',
        effects: {
          treasury: -500,
          popularity: 4,
          gdp: -0.1,
          inflation: 0.1,
          unemployment: 0,
        },
      },
      {
        id: 'opt_b',
        title: 'Request State + Central Coordination',
        description: 'Coordinate joint relief operations with state authorities, matching state funds with central emergency support.',
        pros: 'Fiscal prudence with shared financial responsibility.',
        cons: 'Moderate approval gains due to shared operational responsibility.',
        effects: {
          treasury: -200,
          popularity: 2,
          gdp: 0.0,
          inflation: 0.0,
          unemployment: 0,
        },
      },
      {
        id: 'opt_c',
        title: 'Wait for Detailed Assessment',
        description: 'Send a parliamentary study committee to survey the damage before approving major relief funds.',
        pros: 'Minimal upfront treasury impact.',
        cons: 'Public backlash for delayed response & localized economic slowdown.',
        effects: {
          treasury: -50,
          popularity: -5,
          gdp: -0.2,
          inflation: 0.0,
          unemployment: 0,
        },
      },
    ],
  },
];
